const levels = new Set(["base", "sdd", "sdd-pro"]);
const skillsModes = new Set(["discover", "install"]);

export class CliError extends Error {}

export function usage() {
  return `Usage: npx create-agent-ready-unraf [directory] [options]

Options:
  --level=base|sdd|sdd-pro  Scaffolding level (default: base)
  --workshop                Add workshop materials for game-development students
  --add gdd-to-sdd          Add the GDD-to-SDD guidance skill (requires SDD)
  --skills=discover|install Use AutoSkills explicitly (Node >=22.6 required)
  --doctor                  Report environment and project readiness
  --dry-run                 Show planned changes without writing files
  --force                   Replace only files generated by this CLI
  -y, --yes                 Skip the AutoSkills installation confirmation
  -h, --help                Show this help
  -v, --version             Show package version`;
}

function optionValue(argument, name, next) {
  if (argument === name) {
    if (!next || next.startsWith("-")) throw new CliError(`${name} requires a value.`);
    return [next, true];
  }
  if (argument.startsWith(`${name}=`)) return [argument.slice(name.length + 1), false];
  return null;
}

export function parseArgs(argv) {
  const options = {
    target: ".",
    level: "base",
    levelExplicit: false,
    workshop: false,
    additions: [],
    skills: null,
    doctor: false,
    dryRun: false,
    force: false,
    yes: false,
    help: false,
    version: false
  };
  let targetProvided = false;

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    const level = optionValue(argument, "--level", argv[index + 1]);
    const add = optionValue(argument, "--add", argv[index + 1]);
    const skills = optionValue(argument, "--skills", argv[index + 1]);

    if (level) {
      options.level = level[0];
      options.levelExplicit = true;
      index += level[1] ? 1 : 0;
    } else if (add) {
      options.additions.push(add[0]);
      index += add[1] ? 1 : 0;
    } else if (skills) {
      options.skills = skills[0];
      index += skills[1] ? 1 : 0;
    } else if (argument === "--workshop") options.workshop = true;
    else if (argument === "--doctor") options.doctor = true;
    else if (argument === "--dry-run") options.dryRun = true;
    else if (argument === "--force") options.force = true;
    else if (argument === "-y" || argument === "--yes") options.yes = true;
    else if (argument === "-h" || argument === "--help") options.help = true;
    else if (argument === "-v" || argument === "--version") options.version = true;
    else if (argument.startsWith("-")) throw new CliError(`Unknown option: ${argument}`);
    else if (!targetProvided) {
      options.target = argument;
      targetProvided = true;
    } else throw new CliError(`Unexpected argument: ${argument}`);
  }

  if (!levels.has(options.level)) throw new CliError(`Unknown level: ${options.level}`);
  if (options.skills && !skillsModes.has(options.skills)) {
    throw new CliError(`Unknown skills mode: ${options.skills}`);
  }
  for (const addition of options.additions) {
    if (addition !== "gdd-to-sdd") throw new CliError(`Unknown add-on: ${addition}`);
  }
  if (options.additions.includes("gdd-to-sdd") && options.level === "base") {
    throw new CliError("The gdd-to-sdd add-on requires --level=sdd or --level=sdd-pro.");
  }
  return options;
}
