const text = (strings, ...values) => String.raw({ raw: strings }, ...values).trimStart();

const agents = text`# Agent Instructions

## Working agreement

- Inspect the repository before proposing edits. State the relevant files, conventions, and verification commands.
- Keep changes small and within the approved scope. Ask for explicit approval in the conversation before deleting or migrating data, publishing, installing dependencies, changing delivery configuration, accessing secrets, or using destructive Git operations.
- Treat plans, tests, builds, captures, and human review as evidence. Do not claim a change works without naming the evidence.
- Preserve existing project conventions. Do not replace project configuration merely to make a task easier.
- Stop and explain when requirements, acceptance criteria, or verification are ambiguous.

## Completion report

Report changed files, verification performed, evidence obtained, limitations, and follow-up decisions for a human.
`;

const discoverySkill = text`---
name: repo-discovery
description: Inspect an existing repository before planning or modifying code. Use for new tasks, unfamiliar projects, or when project conventions are unclear.
---

# Repository Discovery

1. Identify the project type, package or engine configuration, source layout, tests, and build commands.
2. Read the closest project instructions before editing.
3. Report facts with file paths. Separate observations from assumptions.
4. Propose the smallest relevant scope and ask questions if acceptance criteria are missing.
`;

const verifySkill = text`---
name: verify
description: Select and run the smallest available verification that supports a software change. Use after planning an implementation and before reporting completion.
---

# Verification

1. Discover existing build, test, lint, engine, and manual-playtest commands.
2. Match verification to the requested change. Do not invent a passing result.
3. Record commands, outcomes, logs, captures, or manual steps as evidence.
4. If verification is unavailable, report the gap and the next human check required.
`;

const sddSpecSkill = text`---
name: sdd-spec
description: Guide a person to define a small, testable software specification before implementation. Use when a request is vague, a change needs scope, or a new SPEC should be drafted.
---

# Define a Spec

Ask about the user value, affected behavior, scope, non-scope, constraints, acceptance criteria, and evidence. Keep the spec small enough for one reviewable change. Do not create a numbered spec or edit code without explicit approval.
`;

const sddPlanSkill = text`---
name: sdd-plan
description: Create a technical plan for an approved specification after inspecting the repository. Use before implementation of a scoped SDD change.
---

# Plan From a Spec

Read the approved spec and repository evidence. Identify files, symbols, dependencies, steps, verification, and stopping conditions. Mark unknowns instead of guessing. Do not implement while planning.
`;

const traceabilitySkill = text`---
name: sdd-traceability
description: Maintain traceability among a specification, plan, tasks, implementation, verification, and evidence. Use for sustained projects, reviews, or when requirements may drift.
---

# Traceability

For every acceptance criterion, identify the planned task, implementation location, verification, and evidence. Surface missing links and risks for human decisions.
`;

const autopsySkill = text`---
name: technical-autopsy
description: Analyze a failed verification, unexpected result, or scope deviation without assigning blame. Use after an SDD cycle does not converge as expected.
---

# Technical Autopsy

Record expectation, observation, evidence, likely causes, decision points, and the smallest corrective action. Distinguish facts from hypotheses.
`;

const gddSkill = text`---
name: gdd-to-sdd
description: Guide game-development students from a Game Design Document toward well-defined SDD specifications and review consistency between the GDD and existing specs. Use when discussing a GDD, game idea, mechanics, design pillars, or alignment between game intent and implementation work.
---

# GDD to SDD

Read the GDD and existing specs before responding. Identify the player fantasy, design pillars, core loop, mechanics, entities, progression, UX, and constraints.

Ask questions that help the person turn one design intention into a small, testable spec. Do not create numbered specs, scenes, assets, or code automatically.

When asked for alignment, produce a report with:

- GDD elements covered by specs.
- GDD elements without an implementation definition.
- Specs without explicit support in the GDD.
- Contradictions, assumptions, and decisions that need human review.
`;

const templates = {
  base: [
    ["AGENTS.md", agents],
    [".agent-ready/README.md", "# Agent-ready harness\n\nThis folder records files generated by `create-agent-ready-unraf`. Keep project-specific agent instructions in `AGENTS.md`.\n"],
    [".opencode/skills/repo-discovery/SKILL.md", discoverySkill],
    [".opencode/skills/verify/SKILL.md", verifySkill]
  ],
  sdd: [
    [".sdd/README.md", "# Spec-Driven Development\n\nUse a spec to define a small change, a plan to inspect the technical path, and evidence to support the result. Specs are human-approved contracts, not automatic code-generation requests.\n\n## Working structure\n\n- Copy a template from `templates/` into `specs/`, `plans/`, or `evidence/`; do not edit the template for a single change.\n- Use the same sortable identifier across related records, for example `001-player-lives.md`.\n- Link the approved spec from its plan, and link the plan and spec from its evidence.\n- Keep records with the code and review them together.\n"],
    [".sdd/specs/.gitkeep", ""],
    [".sdd/plans/.gitkeep", ""],
    [".sdd/evidence/.gitkeep", ""],
    [".sdd/templates/spec.md", "# SPEC: <short title>\n\n## Problem and player or user value\n\n## Current and expected behavior\n\n## Related GDD or design reference\n\n## Scope\n\n## Non-scope\n\n## Constraints and assumptions\n\n## Acceptance criteria\n- [ ] \n\n## Evidence expected\n\n## Open questions\n\n## Human approval\n- Status: draft | approved | rejected\n- Approved by:\n- Date:\n"],
    [".sdd/templates/plan.md", "# Plan: <spec title>\n\n## Source spec\n- Path:\n- Approval status:\n\n## Repository evidence\n\n## Proposed steps\n1. Step:\n   Criteria covered:\n\n## Files and symbols\n\n## Verification\n\n## Stopping conditions\n"],
    [".sdd/templates/evidence.md", "# Evidence: <spec title>\n\n## Source records\n- Spec:\n- Plan:\n\n## Verification by acceptance criterion\n\n| Criterion | Verification command or manual steps | Expected result | Observed result | Evidence path or link | Limitations |\n| --- | --- | --- | --- | --- | --- |\n|  |  |  |  |  |  |\n\n## Result and follow-up\n"],
    [".opencode/skills/sdd-spec/SKILL.md", sddSpecSkill],
    [".opencode/skills/sdd-plan/SKILL.md", sddPlanSkill]
  ],
  pro: [
    [".sdd/templates/tasks.md", "# Tasks: <spec title>\n\n| Task | Acceptance criterion | Owner | Status | Evidence |\n| --- | --- | --- | --- | --- |\n|  |  |  |  |  |\n"],
    [".sdd/templates/traceability.md", "# Traceability: <spec title>\n\n| Criterion | Plan step | Change | Verification | Evidence |\n| --- | --- | --- | --- | --- |\n|  |  |  |  |  |\n"],
    [".sdd/templates/risk-and-rollback.md", "# Risks and rollback: <spec title>\n\n## Risks and impact\n\n## Stopping conditions and triggers\n\n## Backup or recovery point\n\n## Rollback owner\n\n## Rollback steps\n\n## Rollback verification\n"],
    [".sdd/templates/autopsy.md", "# Technical autopsy\n\n## Expected result\n\n## Observation and evidence\n\n## Affected scope and impact\n\n## Causes to investigate\n\n## Decision and next action\n\n## Preventive action\n\n## Correction verification\n"],
    [".opencode/skills/sdd-traceability/SKILL.md", traceabilitySkill],
    [".opencode/skills/technical-autopsy/SKILL.md", autopsySkill],
    [".github/pull_request_template.md", "## Summary\n\n## Related spec\n\n## Acceptance criteria and evidence\n\n| Criterion | Evidence |\n| --- | --- |\n|  |  |\n\n## Risks or rollback\n\n## Human review checklist\n- [ ] Scope is understood\n- [ ] Acceptance criteria have evidence\n- [ ] Limitations are stated\n"]
  ],
  workshop: [
    [".agent-ready/workshop/guia-de-inicio.md", "# Workshop: getting started\n\n1. Review the paths that would be created: `npx create-agent-ready-unraf . --level=sdd --workshop --dry-run`.\n2. Apply the scaffold only after reviewing those paths: `npx create-agent-ready-unraf . --level=sdd --workshop`.\n3. Complete the game idea or bring an existing GDD.\n4. Define one small spec before asking an agent to edit code.\n5. Inspect the plan, approve the scope, and retain evidence.\n"],
    [".agent-ready/workshop/checklist-de-progreso.md", "# Workshop checklist\n\n- [ ] Project available; a Git repository is recommended for diffs and evidence\n- [ ] Game idea or GDD available\n- [ ] First spec has scope, non-scope, and human approval\n- [ ] Plan references repository evidence and the approved spec\n- [ ] Verification and limitations recorded for each acceptance criterion\n"],
    [".agent-ready/workshop/checklist-de-cierre.md", "# Workshop closure\n\n- [ ] I can explain the difference between a GDD and a spec.\n- [ ] I reviewed a plan before implementation.\n- [ ] I can name the evidence for the latest change.\n- [ ] I know what requires a human decision.\n"],
    ["docs/game/idea-de-juego.md", "# My game idea\n\n## Player fantasy\n\n## Core loop\n\n## Design pillars\n\n## First playable version\n\n## Out of scope for now\n"],
    ["docs/game/gdd-breve.md", "# Brief Game Design Document\n\n## Premise and audience\n\n## Player fantasy\n\n## Player experience\n\n## Core loop\n\n## Design pillars\n\n## Core mechanics\n\n## Rules, win and loss conditions\n\n## Progression or session structure\n\n## First playable version\n\n## Art, sound, and interface notes\n\n## Technical constraints\n"],
    [".sdd/templates/game-spec.md", "# Game spec: <short title>\n\n## Player intention\n\n## Related GDD and design pillar\n\n## Current and expected playable behavior\n\n## Playable scope\n\n## Non-scope\n\n## Rules and constraints\n\n## Acceptance criteria\n- [ ] \n\n## Evidence expected\n\n## Open questions and assumptions\n\n## Human approval\n- Status: draft | approved | rejected\n- Approved by:\n- Date:\n" ]
  ],
  gdd: [
    [".opencode/skills/gdd-to-sdd/SKILL.md", gddSkill],
    [".sdd/templates/gdd-alignment-report.md", "# GDD to SDD alignment\n\n## GDD elements covered by specs\n\n## GDD elements without specs\n\n## Specs without explicit GDD support\n\n## Contradictions or assumptions\n\n## Human decisions required\n"]
  ]
};

export function filesFor(options) {
  const files = [...templates.base];
  if (options.level === "sdd" || options.level === "sdd-pro") files.push(...templates.sdd);
  if (options.level === "sdd-pro") files.push(...templates.pro);
  if (options.workshop) files.push(...templates.workshop);
  if (options.additions.includes("gdd-to-sdd")) files.push(...templates.gdd);
  return files.map(([path, content]) => ({ path, content }));
}
